### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by IceClear** [lucidrains/gigagan-pytorch#1]
Thanks for the great work!
May I know when will the pretrained models be available?
Thanks.

**Comment by ExponentialML** [comment]
Somebody can correct me if I'm wrong, but the compute necessary to release pretrained models for this project would be fairly expensive.

For reference, we're going into the territories of Stable Diffusion type compute cost (6-7 figures), so our only options are a community effort (distributed training), or wait for the research group to release models.

I'm finding it more interesting in what the community will take from this implementation and implement it into their own pipelines (I'm looking at the up scaling mechanism personally).

**Comment by Jainam213** [comment]
Ig google GRC can be used lucidrains should get access easily

**Comment by shangdibufashi** [comment]
looking forward to the weights

**Comment by lucidrains** [comment]
join laion
