### ISSUE TITLE
Insert the attention mechanism in the codes to the stylegan2-ada but fail

### ISSUE THREAD

**Issue by landian60** [lucidrains/gigagan-pytorch#10]
Hello, first of all, thank you for your great work. 
I just inserted the self-attention and cross-attention module to stylegan2-ada, following behind the conv1 SynthesisLayer on the 4,8,16,32 resolution. And I use the CLIP to extract txt features and the contrastive loss. However, after a few iterations, the resulting pictures became completely the same color. Could you please give me some advice on how to improve it?

**Comment by lucidrains** [comment]
@landian60 i can do a quick review of your integration code if you have a public repo or a gist

**Comment by lucidrains** [comment]
i'm actually not too sure if they also used the l2 distance attention for cross attention as well as the extra transformer blocks they appended to the clip text encoder

maybe i should make it an option to fallback to regular attention

**Comment by landian60** [comment]
@lucidrains Thanks for your kindness! 
The results changed after a few modifications, and I will keep training to see what happens.
By the way, I am curious  why you dont't let the style codes participate in the attention process? for example, let the style codes modulate the weight of q&k on self-attention.
Tks.

**Comment by lucidrains** [comment]
glad to hear it is working!

the style codes already participate in modulating the convolutional kernels. as for the text conditioning, that is cross attended to by each image feature map token

**Comment by landian60** [comment]
tks! You are so nice. Waiting for your continuing work.

**Comment by landian60** [comment]
Hello Phil,
I have a question about training the model with cross attention.I only used clip contrastive loss and did not add any other losses. And the generative results always became the same color and the G loss was very big even to NaN. I think the reason is the model collapse. Have you encountered similar issues when training the model?
I am planning to add some losses to train the model.

**Comment by landian60** [comment]
@lucidrains
