### ISSUE TITLE
L2 attention is implemented wrong!

### ISSUE THREAD

**Issue by PeterL1n** [lucidrains/gigagan-pytorch#14]
From paper
https://arxiv.org/pdf/2006.04710.pdf

First, token needs to attend itself to ensure Lipschitz!

![image](https://github.com/lucidrains/gigagan-pytorch/assets/7651753/69cb95fe-1cf1-4baa-9d9a-f1af38b48462)

Second, `torch.cdist` is not the correct way to do it. Follow the original paper.

![image](https://github.com/lucidrains/gigagan-pytorch/assets/7651753/ad632cf0-a864-4b33-b1b9-41e57b886110)

for tied qk
```python
AB = torch.matmul(qk, qk.transpose(-1, -2))
AA = torch.sum(qk ** 2, -1, keepdim=True)
BB = AA.transpose(-1, -2)    # Since query and key are tied.
attn = -(AA - 2 * AB + BB)
attn = attn.mul(self.scale).softmax(-1)
```

for separate qk
```python
AB = torch.matmul(q, k.transpose(-1, -2))
AA = torch.sum(q ** 2, -1, keepdim=True)
BB = torch.sum(k ** 2, -1, keepdim=True).transpose(-1, -2)
attn = -(AA - 2 * AB + BB)
attn = attn.mul(self.scale).softmax(-1)
```

This is basically `torch.cdist().square()`, but more efficient and supports double backward for r1 regularization.

Last, I believe the paper only used L2 self attention in discriminator. The generator should still use dot attention.

**Comment by lucidrains** [comment]
@PeterL1n thanks Peter! will get this all resolved this weekend

did they end up using tied qk for their final model?

**Comment by lucidrains** [comment]
@PeterL1n this is news to me that they are using the squared of the euclidean distance; i will reread the original paper, thank you!

**Comment by lucidrains** [comment]
@PeterL1n if the token attends to itself, wouldn't it always have a distance of 0 and attend to itself the most? maybe it works out for their Lipschitz proof, but how does this make sense in the tied scenario?

**Comment by PeterL1n** [comment]
The paper only proved that L2 attention with tied qk is Lipschitz for self attention, it is not Lipschitz for cross attention, that is why in GigaGAN's discriminator, only self attention is used. However, they used self & cross in generator, knowing that generator can't be Lipschitz, there is no point in using L2 attention in generator, so I believe they used regular dot product for the generator. Their paper also only mentioned L2 attention for the discriminator.

You are correct that in the case of tied qk, token's self distance is always zero, thus always the most similar. So self value is always included in the attention. Other position can have close L2 distance to take away the proportion to self token.

This is my understanding.

**Comment by lucidrains** [comment]
Let's roll with that! Thank you Peter for the review 🙏

**Comment by lucidrains** [comment]
it would be euclidean distance squared, so it would have to be quite close. thinking out loud

**Comment by lucidrains** [comment]
@PeterL1n do you want to see if 0.0.17 unblocks you for your research / startup?

**Comment by lucidrains** [comment]
@PeterL1n reviewed the old deepmind paper and indeed it is squared distance! thanks for catching this and correcting my misunderstanding

**Comment by lucidrains** [comment]
closing as it should be resolved, feel free to reopen if you note any further issues
