### ISSUE TITLE
Generator/Discriminator dim Argument

### ISSUE THREAD

**Issue by CerebralSeed** [lucidrains/gigagan-pytorch#26]
It seems that the current implementation of the Generator/Discriminator do not make any use of the primary `dim` argument. Looks like `capacity` is the main "go to" for altering the overall model size on the z dimension. 

Perhaps `dim` could be removed, or the term `capacity` could be replaced with `dim`.

**Comment by lucidrains** [comment]
@CerebralSeed oh yes, decided to rename this `dim_capacity` :laughing:

**Comment by lucidrains** [comment]
thanks!
