### ISSUE TITLE
Why change the collection of rgb in upsampler?

### ISSUE THREAD

**Issue by XavierXiao** [lucidrains/gigagan-pytorch#30]
Hi! Noticed that in a recent commit, you change [this line](https://github.com/lucidrains/gigagan-pytorch/blob/main/gigagan_pytorch/unet_upsampler.py#L587C9-L587C70), but isn't the original version with >= correct? It returned the rgbs with size greater than input size, while now it returns less than or equal to input size.

**Comment by lucidrains** [comment]
@XavierXiao wasn't thinking clearly this morning :disappointed: should be [fixed](https://github.com/lucidrains/gigagan-pytorch/commit/8dd05149035e2787a634b5ec4d1c41c99f83885a) !
