### ISSUE TITLE
Some doubts about the multi-scale input and output of the super-resolution part

### ISSUE THREAD

**Issue by boya34** [lucidrains/gigagan-pytorch#31]
Hello, thanks for your coding. While trying this code, I found out that the resolutions of "multiscale_input_resolutions" and "rbgs"  were mismatched. My understanding of the paper is that the size of the multi-scale input is smaller than the original image. in your code that you preserve larger sizes than the original image in order to preserve more features. I'm confused about it and hope for your reply.

**Comment by lucidrains** [comment]
@boya34 it isn't the original image, but the low resolution image being given to the unet

**Comment by boya34** [comment]
thank you for your reply, but I still feel a bit confused, let me explain in more detail. 
As the paper says, the input image size of unet is 64 pixels, and the output image size is 512 pixels, so in version 0.2.6 the allowable rgb resolutions is [128, 256](bigger than 64 and smaller than 512), while the multiscale_input_resolutions is [64, 32, 16, 8], this mismatching will lead to an error (the related assertion is around line 1841 in gigagan_pytorch.py).
 Besides, the rgbs choose the size bigger than original size which is 64 (in unet_upsampler.py), so the rgb_index is [128, 256, 512] , but it should be the same as multiscale_input_resolutions(the related assertion is around line 1627 in gigagan_pytorch.py).
The paper says the generator producing a pyramid {xi}, and  x0 is the full image(64 pixels I guess), so I understand the meaning of multiscale_input_resolutions, could you please tell me more about the other two arrays? thanks a lot.

**Comment by lucidrains** [comment]
are you asking why the allowable rgbs are the way they are, or how to configure the discriminator to remove the error?

**Comment by lucidrains** [comment]
@boya34 you can resolve this error (and perhaps i should auto-resolve it for unet as it is confusing), by setting `Discriminator(multiscale_input_resolutions = unet.allowable_rgb_resolutions)`

i have also decided to just default to sending the discriminator the low resolution image as the lowest resolution rgb always

**Comment by boya34** [comment]
@lucidrains  if the value could be changed, I think I can fix it. Thank you again!

**Comment by lucidrains** [comment]
no problem, happy training!
