### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by kaykyr** [lucidrains/gigagan-pytorch#32]
I'd like to suggest inform on readme about minimum hardware requirements for training.

I am new on this scenario, I am trying to study about all these technologies recently, and I also would like to know about these requirements, because I recently purchased a very simple computer machine to start my studies.

Is this project able to run on my weak machine?

Core i9 12900HK Interposed @ 5,0GHz
DDR4 64GB RAM
1 x RTX 4090 24GB GDDR6X

I know some generatives models that will run pretty on this hardware, but some text models like Llama requires much more RAM/VRAM memory to run.

Im planning aquiring more GPUs in the future, but I think these modest hardware will work very well to start study journey.

So guys, what you can share about which hardware will be pretty well to run training and inferences?

**Comment by axel578** [comment]
Just a quick note, not model are officially relaesed from this repo, so you have to train from scratch, the computing requirements scales depending on the number of parameters you are creating for your model, a rtx 4090 is more than enough if you make a small model with small images, but if you choose bigger paramters in the gan architecture, the memory requirements will scale accordingly, the best would be to start with a small model, take the example code provided, and experiment with the parameters, most of all the GigaGan parameters of the class in the code example will scale memory requirements up.

This repo is pretty new, you may want to use imagen-pytorch.

**Comment by lucidrains** [comment]
yea agreed with Axel. a lot of research papers have already came out using imagen-pytorch, while gigagan is still fairly new and no reported success training it

**Comment by kaykyr** [comment]
Thank you guys! Thank you for sharing a bit of knowledge with me. I'll study imagen-pytorch.

**Comment by lucidrains** [comment]
@kaykyr thanks for the small sponsorship!
