### ISSUE TITLE
Possible Discrepancies

### ISSUE THREAD

**Issue by randintgenr** [lucidrains/gigagan-pytorch#33]
Hi Phil,

I noted a few possible discrepancies, and I have made some suggestions as well.

You may want to consider;

1. Turning off Demodulation for ToRGB
 The demodulation is turned on in the ToRGB. In the current implementation, ToRGB uses`demod=True`.  This makes it a lot harder for the generator to get the correct feature magnitude at each level of the progressive growing pathway.

2. Removing sample adaptive kernels in the ToRGB component
I don't believe that SAKS is used by GigaGAN in the ToRGB section. The caption of Figure 4 states "The style code modulates the main generator using our style-adaptive kernel selection, shown on the right". The main generator is the upsampling pathway consisting of style based feature modulation, not the progressive growing section.  The output of the ToRGB section is three channels, so adding more kernel probably won't improve representational capacity but lead to oscillations.

**Comment by lucidrains** [comment]
@randintgenr thank you Keerth from down under! i'll get this fixed latest monday morning!

**Comment by lucidrains** [comment]
@randintgenr decided to just address it this morning, since i'm excited you are testing it out! let me know if these changes help

**Comment by samtlyoung** [comment]
@randintgenr saw your recent contributions! We have been working on a new foundational model and would love to pick your brain / chat. Given your graphics focus, I think you will find it interesting! Can you ping me at sam@withpoly.com
