### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by dprze** [lucidrains/gigagan-pytorch#36]
Hi, I ran into some problems while trying to launch training on multi gpu (one machine):

- First, there were problems with `DistributedDataParallel` missing some fields in `gigagan_pytorch.py`: `self.D.multiscale_input_resolutions` in line 2159 and `self.G.input_image_size` in 2095. For a quick fix I added `module` before referencing a field and moved on.
- Then I got a following error: `RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update` originating from `gigagan_pytorch.py` line 2514 (2479). I tried to clone the generator output for a quick fix (as well as sample function output), but it didn't help.

I use accelerate for the first time, so no prior experience - while running on single GPU everything works fine.
Since multi gpu training is marked in your todo list as done, I suppose the issue is on my side - but maybe you have some idea what causes those problems? I use `torch 2.0.1+cu117`, `accelerate 0.22.0`.

Anyway, thanks for great work!

**Comment by lucidrains** [comment]
@dprze thanks Dominika!

took care of the first bullet point, but wasn't sure if you gave me the right line for the second, as i don't see any inplace updates

did you mean this line? https://github.com/lucidrains/gigagan-pytorch/blob/main/gigagan_pytorch/gigagan_pytorch.py#L2479

**Comment by lucidrains** [comment]
@dprze spotted a few issues and put in a few fixes

i don't have access to my deep learning rig (w/ multi-gpus), so let me know if it works or not

**Comment by dprze** [comment]
@lucidrains thank you, now I'm able to run multi gpu training - although for some reason one iteration takes longer than on single gpu ;)

sorry for the line mix-up, it was 2479 indeed, but I was confused as I couldn't find the troublesome inplace operation myself

**Comment by lucidrains** [comment]
no problem! happy training!

I spent a year a long time ago training GANs and would not wish it on my worst enemy 🤣
