### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by AceBeaker2** [lucidrains/gigagan-pytorch#4]
I'm sorry for leaving such an annoying issue, but how can I use this as a package for txt2img/upscaling?

**Comment by lucellent** [comment]
Wondering the same.
Seems like the authors haven't published any source codes or anything like that.

**Comment by bbecausereasonss** [comment]
Unclear. Probably need models.

**Comment by lucidrains** [comment]
the authors are not planning on open sourcing neither the code or models

this is an unofficial project and not completed yet (but will be)

watch for the wip flag to removed

**Comment by ARTUROSING** [comment]
Is it possible to recreate GigaGAN using only paper and existing technology?

**Comment by TortoiseFanboy** [comment]
> Is it possible to recreate GigaGAN using only paper and existing technology?

Yeah.... That's what lucid just did
