### ISSUE TITLE
Wrong order of resolutions list

### ISSUE THREAD

**Issue by inspirit** [lucidrains/gigagan-pytorch#44]
The order of resolutions are from high to low in generator:
https://github.com/lucidrains/gigagan-pytorch/blob/9a364dd33cf0ff053ea01041e02bc41949e53609/gigagan_pytorch/gigagan_pytorch.py#L919C9-L919C20

should be reversed I suppose?

**Comment by lucidrains** [comment]
@inspirit hey, thanks for the code review! should be fixed
