### ISSUE TITLE
to_rgb branch has only 1 learnable kernel

### ISSUE THREAD

**Issue by inspirit** [lucidrains/gigagan-pytorch#45]
to_rgb Conv has only 1 learnable kernel but we add more here:
https://github.com/lucidrains/gigagan-pytorch/blob/9a364dd33cf0ff053ea01041e02bc41949e53609/gigagan_pytorch/gigagan_pytorch.py#L995C20-L995C20

**Comment by inspirit** [comment]
this doesnt fix the issue i'm talking about:
            to_rgb = AdaptiveConv2DMod(dim_out, channels, 1, num_conv_kernels = 1, demod = False)
num_conv_kernels is always 1 for rgb regardless of Generator setting

**Comment by lucidrains** [comment]
@inspirit yup, that is intentional, based on point 2 in https://github.com/lucidrains/gigagan-pytorch/issues/33

**Comment by inspirit** [comment]
but you still compute kernel weights for rgb branch

style_embed_split_dims.extend([
                dim_in,             # for first conv in resnet block
                dim_kernel_mod,     # first conv kernel selection
                dim_out,            # second conv in resnet block
                dim_kernel_mod,     # second conv kernel selection
                dim_out,            # to RGB conv
                dim_kernel_mod,     # RGB conv kernel selection
            ])

**Comment by lucidrains** [comment]
@inspirit :man_facepalming: yes you are right

**Comment by inspirit** [comment]
but i agree that this path looks super convoluted :) i would rather move mod+kernel_mod projection inside AdaptiveConv2DMod

**Comment by lucidrains** [comment]
@inspirit yes i'll get around to it :sweat_smile:
