### ISSUE TITLE
Loss turned `NaN` when custom training

### ISSUE THREAD

**Issue by yasohasakii** [lucidrains/gigagan-pytorch#56]
Hi , I met the`loss nan` issue too, and I added `torch.autograd.set_detect_anomaly(True)` then  got `RuntimeError: Function 'MulBackward0' returned nan values in its 1th output. `. The gigagan-python of mine is 0.2.20, how can I fix this issue, please!

**Comment by yasohasakii** [comment]
I have set `vision_aided_divergence_loss_weight=0.` and still got wrong like below, please help me if you are convenient, thanks!
![image](https://github.com/lucidrains/gigagan-pytorch/assets/20236150/15845a8d-c78d-4576-be65-60fede712699)

**Comment by Lil-Air** [comment]
> I have set `vision_aided_divergence_loss_weight=0.` and still got wrong like below, please help me if you are convenient, thanks! ![image](https://private-user-images.githubusercontent.com/20236150/340985110-15845a8d-c78d-4576-be65-60fede712699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDU2NzQsIm5iZiI6MTcyOTg0NTM3NCwicGF0aCI6Ii8yMDIzNjE1MC8zNDA5ODUxMTAtMTU4NDVhOGQtYzc4ZC00NTc2LWJlNjUtNjBmZWRlNzEyNjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4MzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OWIzN2U4NmQ0ZGQyZDRjMjMzMDI3ZWU3YjA1NjU0MzNjMTNhZmEwYjVmMTM1NTEwMjBiOWMwZjMxNDc3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CvvPMyMPgmnWrav4g2nGzFkvocu8m3WhLy19ICpThqI)

I have this problem too. Do you solve it?

**Comment by yasohasakii** [comment]
> > I have set `vision_aided_divergence_loss_weight=0.` and still got wrong like below, please help me if you are convenient, thanks! ![image](https://private-user-images.githubusercontent.com/20236150/340985110-15845a8d-c78d-4576-be65-60fede712699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDU2NzQsIm5iZiI6MTcyOTg0NTM3NCwicGF0aCI6Ii8yMDIzNjE1MC8zNDA5ODUxMTAtMTU4NDVhOGQtYzc4ZC00NTc2LWJlNjUtNjBmZWRlNzEyNjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4MzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OWIzN2U4NmQ0ZGQyZDRjMjMzMDI3ZWU3YjA1NjU0MzNjMTNhZmEwYjVmMTM1NTEwMjBiOWMwZjMxNDc3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CvvPMyMPgmnWrav4g2nGzFkvocu8m3WhLy19ICpThqI)
> 
> I have this problem too. Do you solve it?

I have given up that repository.
