### ISSUE TITLE
Is this project ready to train?

### ISSUE THREAD

**Issue by kaykyr** [lucidrains/gigagan-pytorch#6]
Is this ready to start training? 

I am very curious about this project, how can you implement things on it without having weigths to check results? How can you make sure wheter is correct implementation?

I am beginning my studies yet, but I have access to a great hardware for training, I don't know if it will be enough, but if does, may I help with first weights.

**Comment by lucidrains** [comment]
@kaykyr no it isn't ready yet

eventually it'll be one command, as i've done [here](https://github.com/lucidrains/lightweight-gan)  and [here](https://github.com/lucidrains/stylegan2-pytorch)
