### ISSUE TITLE
License Violation Issue

### ISSUE THREAD

**Issue by CerebralSeed** [lucidrains/gigagan-pytorch#8]
Hello Phil, 

Thanks for the work you do. Someone else has been copying your code without respecting your MIT license and including your name, or any reference to you, whatsoever. Please see here:

https://github.com/jianzhnie/GigaGAN

His code updates to nearly identical to yours within a day of you making any updates. As you can see, I made an issue on his project page to address the licensing issue, which he closed without updating the license agreement or making any mention of you. 

Here is how to request a DMCA page takedown in the instance of license violations:
https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice

Just wanted to bring this to your attention.

Cheers

**Comment by lucidrains** [comment]
@CerebralSeed oh hey, yea, that's perfectly fine

the giving is unconditional

**Comment by lucidrains** [comment]
i'm not legally inclined, but i thought MIT was the most unrestrictive license? can DMCA even be enforced?

**Comment by CerebralSeed** [comment]
Okay. That's entirely your call. You would just want to remove these two lines in the license:

"The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

**Comment by lucidrains** [comment]
@CerebralSeed ohh got it, yea i'm just using the default MIT template

**Comment by lucidrains** [comment]
@CerebralSeed i just feel bad for whoever ends up employing him! seems like he's trying to game the system ha
