### ISSUE TITLE
Question about the timing and complexity of GigaGAN replication

### ISSUE THREAD

**Issue by ARTUROSING** [lucidrains/gigagan-pytorch#9]
How long would it take to do a full replication?
And how workable will it be in terms of what is presented in the official article? 
As I understand it, you are using existing technology and adapting something as needed? 

I am overwhelmed by your enthusiasm and desire to make available what is not publicly available to all. 

It deserves a lot of respect, you are making a huge contribution to the evolution of new technologies by making them openly available, overcoming many questions and challenges!

**Comment by lucidrains** [comment]
Hi! Thanks for the kind words

The training details are documented in the appendix of the paper. I believe it was somewhere on the order of a million steps on Laion dataset with batch size of 256

**Comment by reynoldscem** [comment]
@lucidrains do you have much intuition for what that is in e.g. A100 hours?

**Comment by lucidrains** [comment]
this is all in the appendix of the paper
